dist: xenial
install:
  - echo TRAVIS_COMMIT=$TRAVIS_COMMIT
  - echo TRAVIS_COMMIT_MESSAGE=$(echo $TRAVIS_COMMIT_MESSAGE | head -n1)
  - echo TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
  - echo TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
  - echo TRAVIS_PULL_REQUEST_SHA=$TRAVIS_PULL_REQUEST_SHA
  - echo TRAVIS_PULL_REQUEST_SLUG=$TRAVIS_PULL_REQUEST_SLUG
  - env
